### ISSUE TITLE
MT6R Crash at Story Mode Chapter 60.

### ISSUE THREAD

**Issue by FestoROG-XS** [ProjectAsakura/OpenParrot#7]
While chapter 60 playing the CG after race finished,the game will crash immediately without any data saving.

(I guess might be some memory address was wrong in the settings...

Anyway,thanks u guys for the amazing functions in MT6R!

**Comment by shiroikitsu8** [comment]
> While chapter 60 playing the CG after race finished,the game will crash immediately without any data saving.
> 
> (I guess might be some memory address was wrong in the settings...
> 
> Anyway,thanks u guys for the amazing functions in MT6R!

mine is fine... story 60 CG after race finished
